language: node_js

os:
  - linux

node_js:
- "0.10"

sudo: false

before_install:
- xgettext --version

install:
- npm install grunt-cli
- npm install
  
script: 
- node_modules/grunt-cli/bin/grunt test

